#!/usr/bin/env perl
use strict;
use warnings;

use Getopt::Long qw(GetOptions);
use Log::Log4perl qw(:easy get_logger);
use Log::Log4perl::MDC;

my $logfile = '/var/log/bad_ips/bad_ips.log';

# Log4perl config (syslog)
my %logcfg = (
  # 'log4perl.rootLogger'                       => 'INFO, SYS',
  'log4perl.rootLogger'                       => 'DEBUG, SYS',
  'log4perl.appender.SYS'                     => 'Log::Log4perl::Appender::File',
  'log4perl.appender.SYS.filename'            => $logfile,
  'log4perl.appender.SYS.mode'                => 'append',
  'log4perl.appender.SYS.ident'               => 'bad_ips',
  'log4perl.appender.SYS.facility'            => 'local0',
  'log4perl.appender.SYS.layout'              => 'Log::Log4perl::Layout::PatternLayout',
  'log4perl.appender.SYS.layout.ConversionPattern' => '%d|%P|%p|%l|%X{THREAD}|%m%n',
);
Log::Log4perl::init(\%logcfg);
Log::Log4perl::MDC->put("THREAD" => "main");

use lib '/usr/local/lib/site_perl';
use BadIPs;
use Config::Tiny;

my $conf_main = '/usr/local/etc/badips.conf';
my $conf_dir  = '/usr/local/etc/badips.d';

my $test_config = 0;
my $dry_run     = 0;

GetOptions(
  'test-config!' => \$test_config,
  'dry-run!'     => \$dry_run,
) or die "Usage: $0 [--test-config] [--dry-run]\n";

# Read log_level from config before initializing logger
my $log_level = 'INFO';
if (-f $conf_main) {
  my $cfg = Config::Tiny->read($conf_main);
  if ($cfg && $cfg->{global} && $cfg->{global}{log_level}) {
    $log_level = uc($cfg->{global}{log_level});
  }
}

# Re-initialize Log4perl with correct log level
$logcfg{'log4perl.rootLogger'} = "$log_level, SYS";
Log::Log4perl::init(\%logcfg);

my $logger = get_logger("BadIPs");
$logger->info("Starting BadIPs application");

my $app = BadIPs->new(
  conf_main => $conf_main,
  conf_dir  => $conf_dir,
  dry_run   => $dry_run,
);

if ($test_config) {
  my ($ok, $msg, $report) = $app->test_config();
  print $report;
  exit($ok ? 0 : 1);
}

$app->run();

$logger->info("BadIPs application exited normally");

exit(0);
