# The key of "active" is required to enable the plugin
# The key of "name" is optional; if not provided, the plugin section name will be used
# All keys are passed to the plugin as configuration parameters
# The same plugin can be used multiple times with different names by creating
# multiple sections with different names.

# 10-sshd.conf
# Configuration for SSH monitoring plugin for BadIPs
# This plugin monitors SSH log files or journald for failed login attempts
# and blocks IPs based on regexp patterns.

[Plugins:GeneralLogMonitor]
active = 1
name = SSH
log_paths = /var/log/auth.log, /var/log/secure
fetch_interval = 2
initial_fetch = 7200
use_cache = 1
journal_unit = ssh.service, sshd.service
# we can monitor via journald, files, auto, or both
# Auto will use journald if it finds an ssh entry on start-up or reload in the last 24 hours, otherwise it will use 
# file monitoring
monitor_method = auto
# Regexp patterns to identify failed SSH login attempts
# (Short Name ::: Regexp Pattern)
# Short name is used for logging and identification purposes
bad_login_pattern_01 = Failed password:::Failed password for .* from
bad_login_pattern_02 = Invalid user:::Invalid user .* from
bad_login_pattern_03 = Authentication Failure:::pam_unix(sshd:auth): authentication failure
bad_login_pattern_04 = Preauth Connection Closed:::Connection closed by .* \[preauth\]
bad_login_pattern_05 = Did not receive identification string:::Did not receive identification string from
# Thresholds for blocking IPs
block_after_n_attempts = 1
block_duration = 86400