# A general file for each Public Blocklist Plugin configuration
# These could each reside in their own file, but for simplicity they are
# all included here.

# Spamhaus Plugin Configuration
# (required*) active - 1 to enable this blocklist plugin, 0 to disable it
# Each plugin MUST have
# * a unique name after Plugins:
# * at least active = 1 to be used; all other parameters are really at the use of the plugin
[PublicBlocklistPlugins:Spamhaus]
active = 1
urls = https://www.spamhaus.org/drop/drop.txt, https://www.spamhaus.org/drop/edrop.txt
fetch_interval = 3600
use_cache = 1
cache_path = /var/cache/badips/


# -- Other Public Blocklist Plugins --
# The remaining plugins from here down are deactivated by default and are here as examples
# These plugins have not been created; that is left to the user as an exercise, if so desired.
# I found Spamhause to be very effective for my use case.
[PublicBlocklistPlugins:Feodotracker]
active = 0
urls = https://feodotracker.abuse.ch/downloads/ipblocklist.txt
fetch_interval = 7200
use_cache = 1
cache_path = /var/cache/badips/


[PublicBlocklistPlugins:Blocklist_de]
active = 0
urls = https://lists.blocklist.de/lists/all.txt
fetch_interval = 10800
use_cache = 1
cache_path = /var/cache/badips/


[PublicBlocklistPlugins:DNSBL_Info]
active = 0
urls = https://www.dnsbl.info/dnsbl-list.php?file=dnslist-ipv4.txt
fetch_interval = 14400
use_cache = 1
cache_path = /var/cache/badips/


[PublicBlocklistPlugins:Malwaredomainlist]
active = 0
urls = http://www.malwaredomainlist.com/hostslist/ip.txt
fetch_interval = 21600
use_cache = 1
cache_path = /var/cache/badips/

